export const initialEvents = [
  {
    id: "AKV-NT-01",
    title_en: "Kala Ranga (Group Talent Showcase)",
    title_kn: "ಕಲಾ ರಂಗ (ತಂಡ ಪ್ರದರ್ಶನ)",
    description_en: "An open stage cultural event where troupes can showcase Karnataka folk and contemporary stage arts.",
    description_kn: "ತಂಡಗಳು ಕರ್ನಾಟಕದ ಜಾನಪದ ಹಾಗೂ ಸಾಂಪ್ರದಾಯಿಕ ಕಲೆಗಳನ್ನು ಪ್ರದರ್ಶಿಸುವ ಮುಕ್ತ ವೇದಿಕೆಯ ಕಾರ್ಯಕ್ರಮ.",
    category: "traditional",
    category_kn: "ಜಾನಪದ & ಸಾಂಪ್ರದಾಯಿಕ",
    event_date: "02-11-2026",
    event_time: "02:00 PM",
    reporting_time: "01:30 PM",
    venue: "Oya Junction, Acharya Campus",
    venue_kn: "ಓಯಾ ಜಂಕ್ಷನ್, ಆಚಾರ್ಯ ಆವರಣ",
    format: "group",
    is_team: true,
    min_team_size: 2,
    max_team_size: 20,
    max_slots: 50,
    registered_count: 4,
    is_active: true,
    rules_en: "1. Follow all instructions given by event coordinators.\n2. Decisions of the judges will be final and binding.\n3. Originality and cultural authenticity are prioritized.",
    rules_kn: "೧. ಆಯೋಜಕರ ಸೂಚನೆಗಳನ್ನು ಕಡ್ಡಾಯವಾಗಿ ಪಾಲಿಸಬೇಕು.\n೨. ತೀರ್ಪುಗಾರರ ತೀರ್ಮಾನವೇ ಅಂತಿಮವಾಗಿರುತ್ತದೆ.\n೩. ಕನ್ನಡತನ, ಸಂಸ್ಕೃತಿ ಮತ್ತು ಸ್ವಂತಿಕೆಗೆ ಆದ್ಯತೆ ನೀಡಲಾಗುವುದು."
  },
  {
    id: "AKV-NT-02",
    title_en: "Yakshagana & Drama Troupe",
    title_kn: "ಯಕ್ಷಗಾನ ಮತ್ತು ನಾಟಕ ತಂಡ",
    description_en: "Traditional coastal Karnataka theatrical dance drama and street play performances.",
    description_kn: "ಕರಾವಳಿ ಕರ್ನಾಟಕದ ಪಾರಂಪರಿಕ ಯಕ್ಷಗಾನ ನೃತ್ಯ ನಾಟಕ ಮತ್ತು ಬೀದಿ ನಾಟಕ ಪ್ರದರ್ಶನ.",
    category: "cultural",
    category_kn: "ಸಾಂಸ್ಕೃತಿಕ",
    event_date: "02-11-2026",
    event_time: "02:00 PM - 05:00 PM",
    reporting_time: "01:30 PM",
    venue: "Open Air Theatre, Acharya",
    venue_kn: "ಬಯಲು ರಂಗಮಂದಿರ, ಆಚಾರ್ಯ",
    format: "group",
    is_team: true,
    min_team_size: 3,
    max_team_size: 15,
    max_slots: 30,
    registered_count: 0,
    is_active: true,
    rules_en: "1. 3 to 15 members per troupe.\n2. Max performance duration: 15 minutes.\n3. Costumes and make-up must reflect traditional authenticity.",
    rules_kn: "೧. ಪ್ರತಿ ತಂಡಕ್ಕೆ ೩ ರಿಂದ ೧೫ ಸದಸ್ಯರು.\n೨. ಗರಿಷ್ಠ ಪ್ರದರ್ಶನ ಸಮಯ: ೧೫ ನಿಮಿಷಗಳು.\n೩. ವೇಷಭೂಷಣ ಮತ್ತು ರಂಗಸಜ್ಜಿಕೆ ಪಾರಂಪರಿಕ ಶೈಲಿಯಲ್ಲಿರಬೇಕು."
  },
  {
    id: "AKV-NT-03",
    title_en: "Bhavageethe & Janapada (Solo Singing)",
    title_kn: "ಭಾವಗೀತೆ & ಜನಪದ ಗೀತೆ (ಏಕವ್ಯಕ್ತಿ ಗಾಯನ)",
    description_en: "Solo vocal competition celebrating timeless Kannada poets (Da.Ra.Bendre, Kuvempu, KSNA) and folk melodies.",
    description_kn: "ಕನ್ನಡದ ಕವಿವರೇಣ್ಯರ ಕವಿತೆಗಳು ಮತ್ತು ಜನಪದ ಗೀತೆಗಳ ಸುಮಧುರ ಏಕವ್ಯಕ್ತಿ ಗಾಯನ ಸ್ಪರ್ಧೆ.",
    category: "music",
    category_kn: "ಸಂಗೀತ",
    event_date: "03-11-2026",
    event_time: "10:30 AM - 01:30 PM",
    reporting_time: "10:00 AM",
    venue: "Seminar Hall 1, Acharya IT",
    venue_kn: "ಸೆಮಿನಾರ್ ಹಾಲ್ ೧, ಆಚಾರ್ಯ ಐ.ಟಿ",
    format: "solo",
    is_team: false,
    min_team_size: 1,
    max_team_size: 1,
    max_slots: 60,
    registered_count: 1,
    is_active: true,
    rules_en: "1. Individual performance only.\n2. Karaoke tracks or live acoustic instruments permitted.\n3. Song must be in Kannada.",
    rules_kn: "೧. ವೈಯಕ್ತಿಕ ಗಾಯನ ಮಾತ್ರ.\n೨. ಕರೋಕೆ ಟ್ರ್ಯಾಕ್ ಅಥವಾ ಅಕೌಸ್ಟಿಕ್ ವಾದ್ಯ ಬಳಸಬಹುದು.\n೩. ಹಾಡು ಶುದ್ಧ ಕನ್ನಡದಲ್ಲಿರಬೇಕು."
  },
  {
    id: "bhavageethe_solo",
    title_en: "Bhavageethe Solo",
    title_kn: "ಭಾವಗೀತೆ ಏಕವ್ಯಕ್ತಿ",
    description_en: "Expressive solo singing of acclaimed Kannada Bhavageethe and classical lyrics.",
    description_kn: "ಭಾವಪೂರ್ಣ ಕನ್ನಡ ಭಾವಗೀತೆಗಳ ಏಕವ್ಯಕ್ತಿ ಗಾಯನ ಸ್ಪರ್ಧೆ.",
    category: "cultural",
    category_kn: "ಸಾಂಸ್ಕೃತಿಕ",
    event_date: "02-11-2026",
    event_time: "10:00 AM",
    reporting_time: "09:30 AM",
    venue: "Acharya Campus",
    venue_kn: "ಆಚಾರ್ಯ ಆವರಣ",
    format: "solo",
    is_team: false,
    min_team_size: 1,
    max_team_size: 1,
    max_slots: 200,
    registered_count: 5,
    is_active: true,
    rules_en: "1. Standard festival rules apply.\n2. Song must be in Kannada.\n3. Time limit: 4 minutes.",
    rules_kn: "೧. ಮಾನಕ ಸಾಂಸ್ಕೃತಿಕ ನಿಯಮಗಳು ಅನ್ವಯಿಸುತ್ತವೆ.\n೨. ಹಾಡು ಕನ್ನಡದಲ್ಲೇ ಇರಬೇಕು.\n೩. ಕಾಲಮಿತಿ: ೪ ನಿಮಿಷಗಳು."
  }
];
